### ISSUE TITLE
Custom Mutators

### ISSUE THREAD

**Issue by MegaManSec** [antonio-morales/Apache-HTTP-Fuzzing#1]
Hi there,

I was going to †ry out these custom mutators but it seems they are a bit.. broken.. e.g. https://github.com/antonio-morales/Apache-HTTP-Fuzzing/blob/7df9ad040387bd7f4c41671c90f0f299788a7854/Custom%20mutators/Mutators_aux.c#L97 references this 'lines' variable, but no such variable exists. I suspect there is some missing include file or something?

Will the full mutator files be uploaded some time? :)

Good job anyways, and nice blog.

Cheers,

**Comment by antonio-morales** [comment]
@MegaManSec yes, this information was included in another file. I've just uploaded the file https://github.com/antonio-morales/Apache-HTTP-Fuzzing/blob/4969e4a32ba7da67c6c7d3575c5583c1e161b660/Custom%20mutators/aux_new.h

Let me know if you have any other question :)

Regards
